CREATE OR REPLACE WAREHOUSE MORTGAGE_WH
  WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

CREATE OR REPLACE WAREHOUSE MORTGAGE_ETL_WH
  WAREHOUSE_SIZE='LARGE' AUTO_SUSPEND=300 AUTO_RESUME=TRUE;

CREATE OR REPLACE DATABASE MORTGAGE_RISK_DB;

CREATE OR REPLACE SCHEMA MORTGAGE_RISK_DB.RAW;
CREATE OR REPLACE SCHEMA MORTGAGE_RISK_DB.CURATED;
CREATE OR REPLACE SCHEMA MORTGAGE_RISK_DB.FEATURE;
CREATE OR REPLACE SCHEMA MORTGAGE_RISK_DB.MART;
CREATE OR REPLACE SCHEMA MORTGAGE_RISK_DB.GOV;
CREATE OR REPLACE SCHEMA MORTGAGE_RISK_DB.OPS;

USE DATABASE MORTGAGE_RISK_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT ff_csv_gz
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  COMPRESSION = AUTO
  NULL_IF = ('NULL','');

CREATE OR REPLACE STAGE stg_mortgage
  FILE_FORMAT = ff_csv_gz;

CREATE OR REPLACE TABLE OPS.file_ingestion_control (
  file_name STRING,
  file_path STRING,
  file_type STRING,
  file_date DATE,
  arrival_ts TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  load_status STRING,
  rows_loaded NUMBER,
  archive_status STRING,
  retention_days NUMBER,
  archive_due_date DATE,
  delete_due_date DATE,
  last_updated_ts TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE OPS.pipeline_run_log (
  run_id STRING,
  pipeline_name STRING,
  step_name STRING,
  status STRING,
  started_ts TIMESTAMP_NTZ,
  ended_ts TIMESTAMP_NTZ,
  message STRING
);
